### ISSUE TITLE
Onnx model problem！

### ISSUE THREAD

**Issue by sunmooncode** [ibaiGorordo/ONNX-CREStereo-Depth-Estimation#1]
In the combined model, the data format containing unk_ is a conversion error or a problem. Can it be avoided?
![image](https://user-images.githubusercontent.com/86471590/163323052-0de7d8dd-cef2-4508-8f50-5b01b25e930c.png)

When I use **tensorrt** to convert the combined model, I get the following error:
```
[2022-04-14 03:45:33   ERROR] [layers.cpp::EinsumLayer::5525] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/layers.cpp::EinsumLayer::5525, condition: nbInputs > 0 && nbInputs <= MAX_EINSUM_NB_INPUTS
)
While parsing node number 113 [Einsum -> "onnx::Mul_589"]:
ERROR: builtin_op_importers.cpp:1336 In function importEinsum:
[8] Assertion failed: layer_ptr && "Input layer is null."
```
Looking forward to your reply！

**Comment by ibaiGorordo** [comment]
Not sure, I have never converted a model to TensorRT, so I don't know what might the issue. Does the Init version work?

I know that @PINTO0309 was able to convert the model, but not sure how he did it.
https://twitter.com/PINTO03091/status/1512712718524252162

**Comment by sunmooncode** [comment]
@ibaiGorordo thanks! The init version gives the same error.
